chunker:
  max_chunk_length: 1000
  xml_tag_depth: ".//DIV8"

embedder:
  model_name: "all-MiniLM-L6-v2"
  batch_size: 32
  device: null  # Will use default device

database:
  db_url: "sqlite:///data/db/regulation_embeddings.db"
  batch_size: 100

processing:
  data_dir: "data/agencies"
  xml_pattern: "*/xml/*.xml"
  log_file: "data/logs/embed_regulations.log"

vector_store:
  type: "faiss"  # Use FAISS by default
  dimension: 384  # Matches the embedding dimension
  index_type: "L2" 